/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Resources;

import java.util.Random;

/**
 *
 * @author l164299
 */
public class GUIM extends javax.swing.JFrame {

    int[] matrix;
    boolean[] chaypi;

    /**
     * Creates new form GUIM
     */
    public GUIM() {
        matrix = new int[81];
        chaypi = new boolean[81];
        poulateMatrix();
        initComponents();
    }

    public void helper() {
        for (int i = 0; i < 81; i++) {
            if (i % 9 == 0) {
                System.out.print("\n");
            }
            System.out.print(matrix[i] + " ");

        }
    }

    public void poulateMatrix() {
        Random rand = new Random();
        for (int i = 0; i < 81; i++) {
            this.matrix[i] = -2; //-2 means not revealed
            this.chaypi[i] = false;
        }
        for (int i = 0; i < 10; i++) {
            int n = rand.nextInt(80) + 0;
            this.matrix[n] = -1;
        }
        helper();
    }

    public boolean reveal(int i) {
        int bCount = 0;
        if (chaypi[i] != true) {
            if (this.matrix[i] != -1) {

                if (i % 9 != 0 && i + 8 < 80 && this.matrix[i + 8] == -1) {
                    bCount++;
                }
                if (i % 9 != 8 && i - 8 > 0 && this.matrix[i - 8] == -1) {
                    bCount++;
                }
                if (i + 9 < 80 && this.matrix[i + 9] == -1) {
                    bCount++;
                }
                if (i - 9 > 0 && this.matrix[i - 9] == -1) {
                    bCount++;
                }
                if (i % 9 != 8 && i + 10 < 80 && this.matrix[i + 10] == -1) {
                    bCount++;
                }
                if (i % 9 != 0 && i - 10 > 80 && this.matrix[i - 10] == -1) {
                    bCount++;
                }
                if (i % 9 != 8 && i + 1 < 80 && this.matrix[i + 1] == -1) {
                    bCount++;
                }
                if (i % 9 != 0 && i - 1 > 0 && this.matrix[i - 1] == -1) {
                    bCount++;
                }
                this.matrix[i] = bCount;
                this.chaypi[i] = true;
            } else {
                return false;
            }
            if (bCount == 0) {
                if (i % 9 != 0 && i + 8 < 80) {
                    reveal(i + 8);
                }
                if (i % 9 != 8 && i - 8 > 0) {
                    reveal(i - 8);
                }
                if (i + 9 < 80) {
                    reveal(i + 9);
                }
                if (i - 9 > 0) {
                    reveal(i - 9);
                }
                if (i % 9 != 8 && i + 10 < 80) {
                    reveal(i + 10);
                }
                if (i % 9 != 0 && i - 10 > 80) {
                    reveal(i - 10);
                }
                if (i % 9 != 8 && i + 1 < 80) {
                    reveal(i + 1);
                }
                if (i % 9 != 0 && i - 1 > 0) {
                    reveal(i - 1);
                }
            }
        } else if (this.matrix[i] == -1) {
            return false;
        }
        return true;

    }
    public void uiButtons()
    {
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        jButton38 = new javax.swing.JButton();
        jButton39 = new javax.swing.JButton();
        jButton40 = new javax.swing.JButton();
        jButton41 = new javax.swing.JButton();
        jButton42 = new javax.swing.JButton();
        jButton43 = new javax.swing.JButton();
        jButton44 = new javax.swing.JButton();
        jButton45 = new javax.swing.JButton();
        jButton46 = new javax.swing.JButton();
        jButton47 = new javax.swing.JButton();
        jButton48 = new javax.swing.JButton();
        jButton49 = new javax.swing.JButton();
        jButton50 = new javax.swing.JButton();
        jButton51 = new javax.swing.JButton();
        jButton52 = new javax.swing.JButton();
        jButton53 = new javax.swing.JButton();
        jButton54 = new javax.swing.JButton();
        jButton55 = new javax.swing.JButton();
        jButton56 = new javax.swing.JButton();
        jButton57 = new javax.swing.JButton();
        jButton58 = new javax.swing.JButton();
        jButton59 = new javax.swing.JButton();
        jButton60 = new javax.swing.JButton();
        jButton61 = new javax.swing.JButton();
        jButton62 = new javax.swing.JButton();
        jButton63 = new javax.swing.JButton();
        jButton64 = new javax.swing.JButton();
        jButton65 = new javax.swing.JButton();
        jButton66 = new javax.swing.JButton();
        jButton67 = new javax.swing.JButton();
        jButton68 = new javax.swing.JButton();
        jButton69 = new javax.swing.JButton();
        jButton70 = new javax.swing.JButton();
        jButton71 = new javax.swing.JButton();
        jButton72 = new javax.swing.JButton();
        jButton73 = new javax.swing.JButton();
        jButton74 = new javax.swing.JButton();
        jButton75 = new javax.swing.JButton();
        jButton76 = new javax.swing.JButton();
        jButton77 = new javax.swing.JButton();
        jButton78 = new javax.swing.JButton();
        jButton79 = new javax.swing.JButton();
        jButton80 = new javax.swing.JButton();
        jButton81 = new javax.swing.JButton();
        jButton82 = new javax.swing.JButton();
        jButton83 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton3.setText("Game");
        jButton3.setFocusPainted(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3);

        jButton2.setText("Help");
        jButton2.setFocusPainted(false);
        jPanel3.add(jButton2);

        jPanel2.setLayout(new java.awt.GridLayout(9, 9));

        jButton4.setBackground(new java.awt.Color(0, 153, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile.png"))); // NOI18N
        jButton4.setPreferredSize(new java.awt.Dimension(65, 41));
        jButton4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile_hover.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4);

        jButton5.setBackground(new java.awt.Color(0, 153, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile.png"))); // NOI18N
        jButton5.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile_hover.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5);

        jButton6.setBackground(new java.awt.Color(0, 153, 255));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile.png"))); // NOI18N
        jButton6.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile_hover.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6);

        jButton7.setBackground(new java.awt.Color(0, 153, 255));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile.png"))); // NOI18N
        jButton7.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile_hover.png"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton7);

        jButton8.setBackground(new java.awt.Color(0, 153, 255));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile.png"))); // NOI18N
        jButton8.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile_hover.png"))); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton8);

        jButton1.setBackground(new java.awt.Color(0, 153, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile.png"))); // NOI18N
        jButton1.setMaximumSize(new java.awt.Dimension(200, 200));
        jButton1.setMinimumSize(new java.awt.Dimension(0, 0));
        jButton1.setPreferredSize(new java.awt.Dimension(30, 30));
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile_hover.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);

        jButton10.setBackground(new java.awt.Color(0, 153, 255));
        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile.png"))); // NOI18N
        jButton10.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile_hover.png"))); // NOI18N
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton10);

        jButton9.setBackground(new java.awt.Color(0, 153, 255));
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile.png"))); // NOI18N
        jButton9.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile_hover.png"))); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton9);

        jButton11.setBackground(new java.awt.Color(0, 153, 255));
        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile.png"))); // NOI18N
        jButton11.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile_hover.png"))); // NOI18N
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton11);

        jButton12.setBackground(new java.awt.Color(0, 153, 255));
        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile.png"))); // NOI18N
        jButton12.setPreferredSize(new java.awt.Dimension(65, 41));
        jButton12.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile_hover.png"))); // NOI18N
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton12);

        jButton13.setBackground(new java.awt.Color(0, 153, 255));
        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile.png"))); // NOI18N
        jButton13.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile_hover.png"))); // NOI18N
        jPanel2.add(jButton13);

        jButton14.setBackground(new java.awt.Color(0, 153, 255));
        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile.png"))); // NOI18N
        jButton14.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile_hover.png"))); // NOI18N
        jPanel2.add(jButton14);

        jButton15.setBackground(new java.awt.Color(0, 153, 255));
        jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile.png"))); // NOI18N
        jButton15.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile_hover.png"))); // NOI18N
        jPanel2.add(jButton15);

        jButton16.setBackground(new java.awt.Color(0, 153, 255));
        jButton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile.png"))); // NOI18N
        jButton16.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile_hover.png"))); // NOI18N
        jPanel2.add(jButton16);

        jButton17.setBackground(new java.awt.Color(0, 153, 255));
        jButton17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile.png"))); // NOI18N
        jButton17.setMaximumSize(new java.awt.Dimension(200, 200));
        jButton17.setMinimumSize(new java.awt.Dimension(0, 0));
        jButton17.setPreferredSize(new java.awt.Dimension(30, 30));
        jButton17.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile_hover.png"))); // NOI18N
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton17);

        jButton18.setBackground(new java.awt.Color(0, 153, 255));
        jButton18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile.png"))); // NOI18N
        jButton18.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile_hover.png"))); // NOI18N
        jPanel2.add(jButton18);

        jButton19.setBackground(new java.awt.Color(0, 153, 255));
        jButton19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile.png"))); // NOI18N
        jButton19.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile_hover.png"))); // NOI18N
        jPanel2.add(jButton19);

        jButton20.setBackground(new java.awt.Color(0, 153, 255));
        jButton20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile.png"))); // NOI18N
        jButton20.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile_hover.png"))); // NOI18N
        jPanel2.add(jButton20);

        jButton21.setBackground(new java.awt.Color(0, 153, 255));
        jButton21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile.png"))); // NOI18N
        jButton21.setPreferredSize(new java.awt.Dimension(65, 41));
        jButton21.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile_hover.png"))); // NOI18N
        jPanel2.add(jButton21);

        jButton22.setBackground(new java.awt.Color(0, 153, 255));
        jButton22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile.png"))); // NOI18N
        jButton22.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile_hover.png"))); // NOI18N
        jPanel2.add(jButton22);

        jButton23.setBackground(new java.awt.Color(0, 153, 255));
        jButton23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile.png"))); // NOI18N
        jButton23.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile_hover.png"))); // NOI18N
        jPanel2.add(jButton23);

        jButton24.setBackground(new java.awt.Color(0, 153, 255));
        jButton24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile.png"))); // NOI18N
        jButton24.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile_hover.png"))); // NOI18N
        jPanel2.add(jButton24);

        jButton25.setBackground(new java.awt.Color(0, 153, 255));
        jButton25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile.png"))); // NOI18N
        jButton25.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile_hover.png"))); // NOI18N
        jPanel2.add(jButton25);

        jButton26.setBackground(new java.awt.Color(0, 153, 255));
        jButton26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile.png"))); // NOI18N
        jButton26.setMaximumSize(new java.awt.Dimension(200, 200));
        jButton26.setMinimumSize(new java.awt.Dimension(0, 0));
        jButton26.setPreferredSize(new java.awt.Dimension(30, 30));
        jButton26.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile_hover.png"))); // NOI18N
        jButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton26ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton26);

        jButton27.setBackground(new java.awt.Color(0, 153, 255));
        jButton27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile.png"))); // NOI18N
        jButton27.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile_hover.png"))); // NOI18N
        jPanel2.add(jButton27);

        jButton28.setBackground(new java.awt.Color(0, 153, 255));
        jButton28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile.png"))); // NOI18N
        jButton28.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile_hover.png"))); // NOI18N
        jPanel2.add(jButton28);

        jButton29.setBackground(new java.awt.Color(0, 153, 255));
        jButton29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile.png"))); // NOI18N
        jButton29.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile_hover.png"))); // NOI18N
        jPanel2.add(jButton29);

        jButton30.setBackground(new java.awt.Color(0, 153, 255));
        jButton30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile.png"))); // NOI18N
        jButton30.setPreferredSize(new java.awt.Dimension(65, 41));
        jButton30.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile_hover.png"))); // NOI18N
        jPanel2.add(jButton30);

        jButton31.setBackground(new java.awt.Color(0, 153, 255));
        jButton31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile.png"))); // NOI18N
        jButton31.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile_hover.png"))); // NOI18N
        jPanel2.add(jButton31);

        jButton32.setBackground(new java.awt.Color(0, 153, 255));
        jButton32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile.png"))); // NOI18N
        jButton32.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile_hover.png"))); // NOI18N
        jPanel2.add(jButton32);

        jButton33.setBackground(new java.awt.Color(0, 153, 255));
        jButton33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile.png"))); // NOI18N
        jButton33.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile_hover.png"))); // NOI18N
        jPanel2.add(jButton33);

        jButton34.setBackground(new java.awt.Color(0, 153, 255));
        jButton34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile.png"))); // NOI18N
        jButton34.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile_hover.png"))); // NOI18N
        jPanel2.add(jButton34);

        jButton35.setBackground(new java.awt.Color(0, 153, 255));
        jButton35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile.png"))); // NOI18N
        jButton35.setMaximumSize(new java.awt.Dimension(200, 200));
        jButton35.setMinimumSize(new java.awt.Dimension(0, 0));
        jButton35.setPreferredSize(new java.awt.Dimension(30, 30));
        jButton35.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile_hover.png"))); // NOI18N
        jButton35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton35ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton35);

        jButton36.setBackground(new java.awt.Color(0, 153, 255));
        jButton36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile.png"))); // NOI18N
        jButton36.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile_hover.png"))); // NOI18N
        jPanel2.add(jButton36);

        jButton37.setBackground(new java.awt.Color(0, 153, 255));
        jButton37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile.png"))); // NOI18N
        jButton37.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile_hover.png"))); // NOI18N
        jPanel2.add(jButton37);

        jButton38.setBackground(new java.awt.Color(0, 153, 255));
        jButton38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile.png"))); // NOI18N
        jButton38.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile_hover.png"))); // NOI18N
        jPanel2.add(jButton38);

        jButton39.setBackground(new java.awt.Color(0, 153, 255));
        jButton39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile.png"))); // NOI18N
        jButton39.setPreferredSize(new java.awt.Dimension(65, 41));
        jButton39.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile_hover.png"))); // NOI18N
        jPanel2.add(jButton39);

        jButton40.setBackground(new java.awt.Color(0, 153, 255));
        jButton40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile.png"))); // NOI18N
        jButton40.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile_hover.png"))); // NOI18N
        jPanel2.add(jButton40);

        jButton41.setBackground(new java.awt.Color(0, 153, 255));
        jButton41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile.png"))); // NOI18N
        jButton41.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile_hover.png"))); // NOI18N
        jPanel2.add(jButton41);

        jButton42.setBackground(new java.awt.Color(0, 153, 255));
        jButton42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile.png"))); // NOI18N
        jButton42.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile_hover.png"))); // NOI18N
        jPanel2.add(jButton42);

        jButton43.setBackground(new java.awt.Color(0, 153, 255));
        jButton43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile.png"))); // NOI18N
        jButton43.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile_hover.png"))); // NOI18N
        jPanel2.add(jButton43);

        jButton44.setBackground(new java.awt.Color(0, 153, 255));
        jButton44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile.png"))); // NOI18N
        jButton44.setMaximumSize(new java.awt.Dimension(200, 200));
        jButton44.setMinimumSize(new java.awt.Dimension(0, 0));
        jButton44.setPreferredSize(new java.awt.Dimension(30, 30));
        jButton44.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile_hover.png"))); // NOI18N
        jButton44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton44ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton44);

        jButton45.setBackground(new java.awt.Color(0, 153, 255));
        jButton45.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile.png"))); // NOI18N
        jButton45.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile_hover.png"))); // NOI18N
        jPanel2.add(jButton45);

        jButton46.setBackground(new java.awt.Color(0, 153, 255));
        jButton46.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile.png"))); // NOI18N
        jButton46.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile_hover.png"))); // NOI18N
        jPanel2.add(jButton46);

        jButton47.setBackground(new java.awt.Color(0, 153, 255));
        jButton47.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile.png"))); // NOI18N
        jButton47.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile_hover.png"))); // NOI18N
        jPanel2.add(jButton47);

        jButton48.setBackground(new java.awt.Color(0, 153, 255));
        jButton48.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile.png"))); // NOI18N
        jButton48.setPreferredSize(new java.awt.Dimension(65, 41));
        jButton48.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile_hover.png"))); // NOI18N
        jPanel2.add(jButton48);

        jButton49.setBackground(new java.awt.Color(0, 153, 255));
        jButton49.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile.png"))); // NOI18N
        jButton49.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile_hover.png"))); // NOI18N
        jPanel2.add(jButton49);

        jButton50.setBackground(new java.awt.Color(0, 153, 255));
        jButton50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile.png"))); // NOI18N
        jButton50.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile_hover.png"))); // NOI18N
        jPanel2.add(jButton50);

        jButton51.setBackground(new java.awt.Color(0, 153, 255));
        jButton51.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile.png"))); // NOI18N
        jButton51.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile_hover.png"))); // NOI18N
        jPanel2.add(jButton51);

        jButton52.setBackground(new java.awt.Color(0, 153, 255));
        jButton52.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile.png"))); // NOI18N
        jButton52.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile_hover.png"))); // NOI18N
        jPanel2.add(jButton52);

        jButton53.setBackground(new java.awt.Color(0, 153, 255));
        jButton53.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile.png"))); // NOI18N
        jButton53.setMaximumSize(new java.awt.Dimension(200, 200));
        jButton53.setMinimumSize(new java.awt.Dimension(0, 0));
        jButton53.setPreferredSize(new java.awt.Dimension(30, 30));
        jButton53.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile_hover.png"))); // NOI18N
        jButton53.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton53ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton53);

        jButton54.setBackground(new java.awt.Color(0, 153, 255));
        jButton54.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile.png"))); // NOI18N
        jButton54.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile_hover.png"))); // NOI18N
        jPanel2.add(jButton54);

        jButton55.setBackground(new java.awt.Color(0, 153, 255));
        jButton55.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile.png"))); // NOI18N
        jButton55.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile_hover.png"))); // NOI18N
        jPanel2.add(jButton55);

        jButton56.setBackground(new java.awt.Color(0, 153, 255));
        jButton56.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile.png"))); // NOI18N
        jButton56.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile_hover.png"))); // NOI18N
        jPanel2.add(jButton56);

        jButton57.setBackground(new java.awt.Color(0, 153, 255));
        jButton57.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile.png"))); // NOI18N
        jButton57.setPreferredSize(new java.awt.Dimension(65, 41));
        jButton57.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile_hover.png"))); // NOI18N
        jPanel2.add(jButton57);

        jButton58.setBackground(new java.awt.Color(0, 153, 255));
        jButton58.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile.png"))); // NOI18N
        jButton58.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile_hover.png"))); // NOI18N
        jPanel2.add(jButton58);

        jButton59.setBackground(new java.awt.Color(0, 153, 255));
        jButton59.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile.png"))); // NOI18N
        jButton59.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile_hover.png"))); // NOI18N
        jPanel2.add(jButton59);

        jButton60.setBackground(new java.awt.Color(0, 153, 255));
        jButton60.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile.png"))); // NOI18N
        jButton60.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile_hover.png"))); // NOI18N
        jPanel2.add(jButton60);

        jButton61.setBackground(new java.awt.Color(0, 153, 255));
        jButton61.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile.png"))); // NOI18N
        jButton61.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile_hover.png"))); // NOI18N
        jPanel2.add(jButton61);

        jButton62.setBackground(new java.awt.Color(0, 153, 255));
        jButton62.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile.png"))); // NOI18N
        jButton62.setMaximumSize(new java.awt.Dimension(200, 200));
        jButton62.setMinimumSize(new java.awt.Dimension(0, 0));
        jButton62.setPreferredSize(new java.awt.Dimension(30, 30));
        jButton62.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile_hover.png"))); // NOI18N
        jButton62.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton62ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton62);

        jButton63.setBackground(new java.awt.Color(0, 153, 255));
        jButton63.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile.png"))); // NOI18N
        jButton63.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile_hover.png"))); // NOI18N
        jPanel2.add(jButton63);

        jButton64.setBackground(new java.awt.Color(0, 153, 255));
        jButton64.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile.png"))); // NOI18N
        jButton64.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile_hover.png"))); // NOI18N
        jPanel2.add(jButton64);

        jButton65.setBackground(new java.awt.Color(0, 153, 255));
        jButton65.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile.png"))); // NOI18N
        jButton65.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile_hover.png"))); // NOI18N
        jPanel2.add(jButton65);

        jButton66.setBackground(new java.awt.Color(0, 153, 255));
        jButton66.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile.png"))); // NOI18N
        jButton66.setPreferredSize(new java.awt.Dimension(65, 41));
        jButton66.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile_hover.png"))); // NOI18N
        jPanel2.add(jButton66);

        jButton67.setBackground(new java.awt.Color(0, 153, 255));
        jButton67.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile.png"))); // NOI18N
        jButton67.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile_hover.png"))); // NOI18N
        jPanel2.add(jButton67);

        jButton68.setBackground(new java.awt.Color(0, 153, 255));
        jButton68.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile.png"))); // NOI18N
        jButton68.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile_hover.png"))); // NOI18N
        jPanel2.add(jButton68);

        jButton69.setBackground(new java.awt.Color(0, 153, 255));
        jButton69.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile.png"))); // NOI18N
        jButton69.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile_hover.png"))); // NOI18N
        jPanel2.add(jButton69);

        jButton70.setBackground(new java.awt.Color(0, 153, 255));
        jButton70.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile.png"))); // NOI18N
        jButton70.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile_hover.png"))); // NOI18N
        jPanel2.add(jButton70);

        jButton71.setBackground(new java.awt.Color(0, 153, 255));
        jButton71.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile.png"))); // NOI18N
        jButton71.setMaximumSize(new java.awt.Dimension(200, 200));
        jButton71.setMinimumSize(new java.awt.Dimension(0, 0));
        jButton71.setPreferredSize(new java.awt.Dimension(30, 30));
        jButton71.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile_hover.png"))); // NOI18N
        jButton71.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton71ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton71);

        jButton72.setBackground(new java.awt.Color(0, 153, 255));
        jButton72.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile.png"))); // NOI18N
        jButton72.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile_hover.png"))); // NOI18N
        jPanel2.add(jButton72);

        jButton73.setBackground(new java.awt.Color(0, 153, 255));
        jButton73.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile.png"))); // NOI18N
        jButton73.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile_hover.png"))); // NOI18N
        jPanel2.add(jButton73);

        jButton74.setBackground(new java.awt.Color(0, 153, 255));
        jButton74.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile.png"))); // NOI18N
        jButton74.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile_hover.png"))); // NOI18N
        jPanel2.add(jButton74);

        jButton75.setBackground(new java.awt.Color(0, 153, 255));
        jButton75.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile.png"))); // NOI18N
        jButton75.setPreferredSize(new java.awt.Dimension(65, 41));
        jButton75.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile_hover.png"))); // NOI18N
        jPanel2.add(jButton75);

        jButton76.setBackground(new java.awt.Color(0, 153, 255));
        jButton76.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile.png"))); // NOI18N
        jButton76.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile_hover.png"))); // NOI18N
        jPanel2.add(jButton76);

        jButton77.setBackground(new java.awt.Color(0, 153, 255));
        jButton77.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile.png"))); // NOI18N
        jButton77.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile_hover.png"))); // NOI18N
        jPanel2.add(jButton77);

        jButton78.setBackground(new java.awt.Color(0, 153, 255));
        jButton78.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile.png"))); // NOI18N
        jButton78.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile_hover.png"))); // NOI18N
        jPanel2.add(jButton78);

        jButton79.setBackground(new java.awt.Color(0, 153, 255));
        jButton79.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile.png"))); // NOI18N
        jButton79.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile_hover.png"))); // NOI18N
        jPanel2.add(jButton79);

        jButton80.setBackground(new java.awt.Color(0, 153, 255));
        jButton80.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile.png"))); // NOI18N
        jButton80.setMaximumSize(new java.awt.Dimension(200, 200));
        jButton80.setMinimumSize(new java.awt.Dimension(0, 0));
        jButton80.setPreferredSize(new java.awt.Dimension(30, 30));
        jButton80.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile_hover.png"))); // NOI18N
        jButton80.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton80ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton80);

        jButton81.setBackground(new java.awt.Color(0, 153, 255));
        jButton81.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile.png"))); // NOI18N
        jButton81.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile_hover.png"))); // NOI18N
        jPanel2.add(jButton81);

        jButton82.setBackground(new java.awt.Color(0, 153, 255));
        jButton82.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile.png"))); // NOI18N
        jButton82.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile_hover.png"))); // NOI18N
        jPanel2.add(jButton82);

        jButton83.setBackground(new java.awt.Color(0, 153, 255));
        jButton83.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile.png"))); // NOI18N
        jButton83.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/tile_hover.png"))); // NOI18N
        jPanel2.add(jButton83);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/circular-clock.png"))); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/bomb.png"))); // NOI18N

        jLabel2.setBackground(new java.awt.Color(51, 89, 160));
        jLabel2.setFont(new java.awt.Font("Swis721 Blk BT", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("0");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel2.setOpaque(true);
        jLabel2.setPreferredSize(new java.awt.Dimension(90, 40));

        jLabel4.setBackground(new java.awt.Color(51, 89, 160));
        jLabel4.setFont(new java.awt.Font("Swis721 Blk BT", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("10");
        jLabel4.setOpaque(true);
        jLabel4.setPreferredSize(new java.awt.Dimension(90, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(405, 405, 405)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(104, 104, 104))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(69, 69, 69)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(99, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 344, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(19, 19, 19))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(48, 48, 48)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(98, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        reveal(5);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton26ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton26ActionPerformed

    private void jButton35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton35ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton35ActionPerformed

    private void jButton44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton44ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton44ActionPerformed

    private void jButton53ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton53ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton53ActionPerformed

    private void jButton62ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton62ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton62ActionPerformed

    private void jButton71ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton71ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton71ActionPerformed

    private void jButton80ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton80ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton80ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        reveal(2);        // TODO add your handling code here:

    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        reveal(0);
        helper();

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        reveal(1);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        reveal(3);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        reveal(4);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        reveal(6);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        reveal(7);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        reveal(8);
        helper();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed

        reveal(10);
        helper();// TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton39;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton40;
    private javax.swing.JButton jButton41;
    private javax.swing.JButton jButton42;
    private javax.swing.JButton jButton43;
    private javax.swing.JButton jButton44;
    private javax.swing.JButton jButton45;
    private javax.swing.JButton jButton46;
    private javax.swing.JButton jButton47;
    private javax.swing.JButton jButton48;
    private javax.swing.JButton jButton49;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton50;
    private javax.swing.JButton jButton51;
    private javax.swing.JButton jButton52;
    private javax.swing.JButton jButton53;
    private javax.swing.JButton jButton54;
    private javax.swing.JButton jButton55;
    private javax.swing.JButton jButton56;
    private javax.swing.JButton jButton57;
    private javax.swing.JButton jButton58;
    private javax.swing.JButton jButton59;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton60;
    private javax.swing.JButton jButton61;
    private javax.swing.JButton jButton62;
    private javax.swing.JButton jButton63;
    private javax.swing.JButton jButton64;
    private javax.swing.JButton jButton65;
    private javax.swing.JButton jButton66;
    private javax.swing.JButton jButton67;
    private javax.swing.JButton jButton68;
    private javax.swing.JButton jButton69;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton70;
    private javax.swing.JButton jButton71;
    private javax.swing.JButton jButton72;
    private javax.swing.JButton jButton73;
    private javax.swing.JButton jButton74;
    private javax.swing.JButton jButton75;
    private javax.swing.JButton jButton76;
    private javax.swing.JButton jButton77;
    private javax.swing.JButton jButton78;
    private javax.swing.JButton jButton79;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton80;
    private javax.swing.JButton jButton81;
    private javax.swing.JButton jButton82;
    private javax.swing.JButton jButton83;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
